<?php
/**
 * Complete Feedback SDK Integration Example
 *
 * This file shows every single option you can pass to SDK::init().
 * In a real plugin you would put this inside your main plugin file
 * or a dedicated bootstrap class.
 *
 * Autoload (Composer):
 *   composer require wpmet/feedback-sdk
 *
 * Autoload (Manual):
 *   require_once plugin_dir_path( __FILE__ ) . 'feedback-sdk/feedback-sdk.php';
 *
 * @package MyPlugin
 */

// ─────────────────────────────────────────────────────────────────────────────
// 1. MINIMAL — only required keys (copy-paste starting point)
// ─────────────────────────────────────────────────────────────────────────────

add_action( 'plugins_loaded', function () {

    \Feedback_SDK\Core\SDK::init([

        // ── REQUIRED ─────────────────────────────────────────────────────────

        /**
         * Human-readable plugin name.
         * Shown in the modal heading: "Why are you deactivating {plugin_name}?"
         *
         * Type   : string
         * Example: 'ElementsKit', 'MetForm', 'ShopEngine'
         */
        'plugin_name' => 'My Awesome Plugin',

        /**
         * WordPress plugin folder slug.
         * MUST match the actual folder name inside /wp-content/plugins/
         * The SDK uses this to find and intercept the Deactivate link.
         *
         * Type   : string
         * Example: 'elementskit-lite', 'metform', 'my-awesome-plugin'
         * ⚠️  Wrong slug = modal never appears.
         */
        'plugin_slug' => 'my-awesome-plugin',

        /**
         * Current plugin version string.
         * Sent to the server so you can track which version was deactivated.
         *
         * Type   : string
         * Example: '1.0.0', MY_PLUGIN_VERSION (your own constant)
         */
        'plugin_version' => MY_PLUGIN_VERSION,

        /**
         * Full URL of the Feedback server's REST collect endpoint.
         * This is the URL of the site where the main Feedback plugin is installed.
         *
         * Type   : string
         * Format : https://{your-server}/wp-json/feedback/v1/collect
         */
        'api_endpoint' => 'https://api.wpmet.com/wp-json/feedback/v1/collect',

        /**
         * API key generated by the main Feedback plugin.
         * Find it at: Plugin Feedback → Settings → API Key
         * Sent in the X-Feedback-API-Key HTTP header.
         *
         * Type   : string
         * ⚠️  Keep this secret — do not commit to public repositories.
         *      Store in wp-config.php or an environment variable.
         */
        'api_key' => defined( 'MY_FEEDBACK_API_KEY' ) ? MY_FEEDBACK_API_KEY : 'fk_xxxxxxxxxxxxxxxx',

    ]);

}, 20 );


// ─────────────────────────────────────────────────────────────────────────────
// 2. COMPLETE — every available option
// ─────────────────────────────────────────────────────────────────────────────

add_action( 'plugins_loaded', function () {

    \Feedback_SDK\Core\SDK::init([

        // ════════════════════════════════════════════════════════════════════
        // REQUIRED
        // ════════════════════════════════════════════════════════════════════

        'plugin_name'    => 'ElementsKit',
        'plugin_slug'    => 'elementskit-lite',
        'plugin_version' => ELEMENTSKIT_VERSION,
        'api_endpoint'   => 'https://api.wpmet.com/wp-json/feedback/v1/collect',
        'api_key'        => defined( 'WPMET_FEEDBACK_KEY' ) ? WPMET_FEEDBACK_KEY : '',

        // ════════════════════════════════════════════════════════════════════
        // BEHAVIOUR
        // ════════════════════════════════════════════════════════════════════

        /**
         * Mark this feedback as coming from the Pro (paid) version.
         * Stored in the is_pro column on the server.
         * Useful for filtering Pro vs Free deactivations in analytics.
         *
         * Type    : bool
         * Default : false
         */
        'is_pro' => defined( 'ELEMENTSKIT_PRO' ) && ELEMENTSKIT_PRO,

        /**
         * Show a GDPR consent checkbox at the bottom of the modal.
         * When the user UNCHECKS it, the admin_email field is sent as an
         * empty string instead of the actual WordPress admin email.
         *
         * Type    : bool
         * Default : false
         * Use when: your users are in the EU or you want explicit consent
         *           before collecting email data.
         */
        'gdpr' => true,

        /**
         * Enable debug mode.
         * - PHP side : logs each SDK event to error_log()
         * - JS side  : logs events to browser console.log()
         *
         * Type    : bool
         * Default : false
         * ⚠️  Set to false in production.
         */
        'debug' => WP_DEBUG,

        /**
         * Custom modal heading question.
         * %s is replaced with plugin_name automatically.
         *
         * Type    : string
         * Default : 'Why are you deactivating %s?'
         */
        'modal_title' => 'Help us improve — why are you deactivating %s?',

        // ════════════════════════════════════════════════════════════════════
        // BRANDING
        // ════════════════════════════════════════════════════════════════════

        /**
         * Text shown in the modal header next to the icon.
         *
         * Type    : string
         * Default : 'Quick Feedback'
         */
        'brand_name' => 'ElementsKit Feedback',

        /**
         * Tabler Icon class used for the brand icon circle.
         * Browse all icons at: https://tabler.io/icons
         * Only used when brand_icon_url is empty.
         *
         * Type    : string
         * Default : 'ti-bolt'
         * Example : 'ti-layers', 'ti-puzzle', 'ti-forms', 'ti-shopping-cart'
         */
        'brand_icon' => 'ti-layers',

        /**
         * Custom image URL for the brand icon.
         * When set, this OVERRIDES brand_icon entirely.
         * Must be a publicly accessible URL (https recommended).
         *
         * Type    : string
         * Default : '' (empty — uses brand_icon instead)
         * Example : 'https://cdn.wpmet.com/elementskit/icon.png'
         */
        'brand_icon_url' => plugins_url( 'assets/images/icon.png', __FILE__ ),

        // ════════════════════════════════════════════════════════════════════
        // TYPOGRAPHY
        // ════════════════════════════════════════════════════════════════════

        /**
         * Font family name used for all modal text.
         * Must match the font loaded via font_url.
         *
         * Type    : string
         * Default : 'DM Sans'
         */
        'font_family' => 'Inter',

        /**
         * Full <link> href for loading the font.
         * Set to '' (empty string) to skip loading — useful if the font
         * is already loaded by your plugin or theme.
         *
         * Type    : string
         * Default : DM Sans from fonts.googleapis.com
         */
        'font_url' => 'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&display=swap',

        /**
         * Base font size in pixels for all modal text.
         * Affects labels, option text, textarea, and buttons.
         *
         * Type    : int   (pixels, without "px")
         * Default : 13
         * Range   : 11–18 recommended
         */
        'font_size_base' => 13,

        // ════════════════════════════════════════════════════════════════════
        // COLORS
        // ════════════════════════════════════════════════════════════════════

        /**
         * Primary accent color.
         * Used for: radio dots, active option border, textarea focus ring.
         * Must be a valid CSS hex color.
         *
         * Type    : string  (hex color)
         * Default : '#9b59e8'
         */
        'primary_color' => '#f59e0b',

        /**
         * CSS background value for the Submit button and brand icon circle.
         * Can be a solid color, gradient, or any valid CSS background value.
         *
         * Type    : string  (CSS background)
         * Default : 'linear-gradient(135deg,#c94cbf,#7b6ef6)'
         */
        'primary_gradient' => 'linear-gradient(135deg, #f59e0b, #ef4444)',

        /**
         * Full-screen backdrop/overlay color behind the modal.
         * Use rgba() for transparency.
         *
         * Type    : string  (CSS color)
         * Default : 'rgba(15,15,30,.55)'
         */
        'bg_overlay' => 'rgba(0, 0, 0, 0.60)',

        /**
         * Modal background color.
         *
         * Type    : string  (hex color)
         * Default : '#ffffff'
         */
        'modal_bg' => '#ffffff',

        /**
         * Modal border-radius in pixels.
         *
         * Type    : int   (pixels, without "px")
         * Default : 20
         */
        'modal_radius' => 16,

        /**
         * Background color of unselected option rows.
         *
         * Type    : string  (hex color)
         * Default : '#faf8ff'
         */
        'option_bg' => '#fef9ee',

        /**
         * Background color of the currently selected option row.
         *
         * Type    : string  (hex color)
         * Default : '#f9f4ff'
         */
        'option_active_bg' => '#fef3c7',

        /**
         * Border color of the currently selected option row.
         * Defaults to primary_color when not set.
         *
         * Type    : string  (hex color)
         * Default : same as primary_color
         */
        'option_active_border' => '#f59e0b',

        /**
         * Primary text color used for option labels and headings.
         *
         * Type    : string  (hex color)
         * Default : '#1a1a2e'
         */
        'text_primary' => '#1c1917',

        /**
         * Muted/secondary text color used for textarea placeholders
         * and helper text.
         *
         * Type    : string  (hex color)
         * Default : '#9ca3af'
         */
        'text_muted' => '#78716c',

        /**
         * Default border color for unselected option rows.
         *
         * Type    : string  (hex color)
         * Default : '#ede8f5'
         */
        'border_color' => '#e7e5e4',

        // ════════════════════════════════════════════════════════════════════
        // BUTTON & UI LABELS  (i18n)
        // ════════════════════════════════════════════════════════════════════

        /**
         * Override any text label shown in the modal.
         * All keys are optional — only override what you need.
         *
         * Type : array
         */
        'i18n' => [

            /**
             * Submit button label.
             * Default: 'Submit & Deactivate'
             */
            'submit' => __( 'Submit & Deactivate', 'my-awesome-plugin' ),

            /**
             * Skip button label (bottom left).
             * Default: 'Skip & Deactivate'
             */
            'skip' => __( 'Skip & Deactivate', 'my-awesome-plugin' ),

            /**
             * Cancel button label (closes modal without deactivating).
             * Default: 'Cancel'
             */
            'cancel' => __( 'Cancel', 'my-awesome-plugin' ),

            /**
             * GDPR consent checkbox label.
             * Only shown when gdpr => true.
             * Default: 'I agree to share this feedback anonymously.'
             */
            'gdpr_label' => __( 'I agree to share this feedback data anonymously.', 'my-awesome-plugin' ),
        ],

        // ════════════════════════════════════════════════════════════════════
        // REASONS  (three mutually exclusive options — pick ONE)
        // ════════════════════════════════════════════════════════════════════

        // ── Option A: Hide specific default reasons ───────────────────────
        //
        // Remove one or more built-in reasons by key.
        // The rest remain in their original order.
        //
        // Available keys:
        //   'no-longer-needed', 'found-better', 'not-working',
        //   'temp-disabled', 'missing-feature', 'too-expensive',
        //   'bug-issue', 'other'
        //
        // 'hide_reasons' => [ 'too-expensive', 'found-better' ],


        // ── Option B: Append extra reasons AFTER the defaults ─────────────
        //
        // Each reason must have these four keys:
        //   key   (string) — unique identifier, sent to server as the reason value
        //   icon  (string) — Tabler Icon class (https://tabler.io/icons)
        //   label (string) — text shown in the modal option row
        //   ph    (string) — textarea placeholder when this option is selected
        //
        // 'extra_reasons' => [
        //     [
        //         'key'   => 'theme-conflict',
        //         'icon'  => 'ti-layout',
        //         'label' => 'Theme or plugin conflict',
        //         'ph'    => 'Which theme or plugin caused the conflict?',
        //     ],
        //     [
        //         'key'   => 'switching-platform',
        //         'icon'  => 'ti-brand-wordpress',
        //         'label' => 'Switching to another platform',
        //         'ph'    => 'Which platform are you moving to?',
        //     ],
        // ],


        // ── Option C: Replace ALL reasons with your own list ──────────────
        //
        // When 'reasons' is set, default reasons are completely ignored.
        // The SDK shows exactly what you define here — no more, no less.
        //
        'reasons' => [
            [
                'key'   => 'no-longer-needed',
                'icon'  => 'ti-plug-off',
                'label' => __( 'I no longer need the plugin', 'my-awesome-plugin' ),
                'ph'    => __( 'What did you use it for?', 'my-awesome-plugin' ),
            ],
            [
                'key'   => 'found-better',
                'icon'  => 'ti-star',
                'label' => __( 'I found a better plugin', 'my-awesome-plugin' ),
                'ph'    => __( 'Which plugin did you switch to?', 'my-awesome-plugin' ),
            ],
            [
                'key'   => 'not-working',
                'icon'  => 'ti-tool',
                'label' => __( "I couldn't get the plugin to work", 'my-awesome-plugin' ),
                'ph'    => __( 'What issue did you face?', 'my-awesome-plugin' ),
            ],
            [
                'key'   => 'temp-disabled',
                'icon'  => 'ti-clock-pause',
                'label' => __( "It's temporarily disabled", 'my-awesome-plugin' ),
                'ph'    => __( 'When do you plan to reactivate?', 'my-awesome-plugin' ),
            ],
            [
                'key'   => 'missing-feature',
                'icon'  => 'ti-puzzle',
                'label' => __( 'Missing a feature I need', 'my-awesome-plugin' ),
                'ph'    => __( 'Which feature is missing?', 'my-awesome-plugin' ),
            ],
            [
                'key'   => 'too-expensive',
                'icon'  => 'ti-currency-dollar',
                'label' => __( 'Too expensive', 'my-awesome-plugin' ),
                'ph'    => __( 'What price would be acceptable?', 'my-awesome-plugin' ),
            ],
            [
                'key'   => 'bug-issue',
                'icon'  => 'ti-bug',
                'label' => __( 'Bug or technical issue', 'my-awesome-plugin' ),
                'ph'    => __( 'Please describe the issue', 'my-awesome-plugin' ),
            ],
            [
                'key'   => 'theme-conflict',          // ← custom key
                'icon'  => 'ti-layout',               // ← custom Tabler icon
                'label' => __( 'Conflict with my theme', 'my-awesome-plugin' ),
                'ph'    => __( 'Which theme are you using?', 'my-awesome-plugin' ),
            ],
            [
                'key'   => 'other',
                'icon'  => 'ti-message-dots',
                'label' => __( 'Other reason', 'my-awesome-plugin' ),
                'ph'    => __( 'Please share your thoughts', 'my-awesome-plugin' ),
            ],
        ],

    ]);

}, 20 );


// ─────────────────────────────────────────────────────────────────────────────
// 3. HOOKS — modify behaviour without editing SDK files
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Add custom data to the payload before it is sent to the server.
 * You can add any extra field here — the server's collect endpoint
 * will receive it (though only the documented fields are stored in the DB).
 *
 * @param array  $payload The full data array being sent.
 * @param string $slug    Your plugin slug.
 * @return array
 */
add_filter( 'feedback_sdk/payload', function ( array $payload, string $slug ): array {

    // Add any extra context you want logged on the server.
    $payload['active_theme']    = get_template();
    $payload['multisite']       = is_multisite() ? 'yes' : 'no';
    $payload['plugin_pro_plan'] = get_option( 'my_plugin_plan', 'free' );

    return $payload;

}, 10, 2 );


/**
 * React after the feedback has been sent (or failed).
 * Use for custom logging, Slack notifications, etc.
 *
 * @param string $slug    Your plugin slug.
 * @param bool   $success Whether wp_remote_post succeeded.
 * @param array  $payload The data that was sent.
 */
add_action( 'feedback_sdk/after_send', function ( string $slug, bool $success, array $payload ): void {

    if ( ! $success ) {
        // Example: log failures to your own error tracking.
        error_log( "[{$slug}] Feedback SDK send failed. Reason: " . ( $payload['reason'] ?? 'unknown' ) );
    }

}, 10, 3 );


/**
 * Modify the reasons list at runtime (server-side, before JS localization).
 * Useful for dynamically showing/hiding reasons based on user role, plan, etc.
 *
 * @param array  $reasons Array of reason objects {key, icon, label, ph}.
 * @param string $slug    Your plugin slug.
 * @return array
 */
add_filter( 'feedback_sdk/reasons', function ( array $reasons, string $slug ): array {

    // Example: hide "Too expensive" for users who already have a Pro licence.
    if ( my_plugin_user_has_licence() ) {
        $reasons = array_filter( $reasons, fn( $r ) => $r['key'] !== 'too-expensive' );
        $reasons = array_values( $reasons ); // re-index
    }

    return $reasons;

}, 10, 2 );


// ─────────────────────────────────────────────────────────────────────────────
// 4. WHAT IS AUTOMATICALLY COLLECTED (no config needed)
// ─────────────────────────────────────────────────────────────────────────────

/*
 * The SDK automatically collects these values from WordPress — you don't
 * need to pass them in the config:
 *
 *   site_url      → get_site_url()
 *   admin_email   → get_option('admin_email')    (empty if gdpr unchecked)
 *   wp_version    → get_bloginfo('version')
 *   php_version   → PHP_MAJOR_VERSION.PHP_MINOR_VERSION
 *   locale        → get_locale()
 *   timestamp     → current_time('mysql')
 *
 * These come from your config:
 *   plugin_name, plugin_slug, plugin_version, is_pro
 *
 * These come from the user's modal input:
 *   reason        → the selected reason key (e.g. 'missing-feature')
 *   message       → text typed in the textarea
 *   competitor    → only filled if the user typed something (no dedicated field by default)
 *
 * These are added by the server (not sent by SDK):
 *   country       → resolved from IP address server-side
 *   ip_address    → detected server-side
 *   status        → defaults to 'new'
 *   created_at    → set by database DEFAULT
 */


// ─────────────────────────────────────────────────────────────────────────────
// 5. PRO vs FREE — separate init calls
// ─────────────────────────────────────────────────────────────────────────────

/*
 * If you maintain separate Free and Pro plugins, initialize the SDK in each:
 *
 * Free plugin (elementskit-lite/elementskit-lite.php):
 *
 *   \Feedback_SDK\Core\SDK::init([
 *       'plugin_name'    => 'ElementsKit',
 *       'plugin_slug'    => 'elementskit-lite',
 *       'plugin_version' => ELEMENTSKIT_VERSION,
 *       'api_endpoint'   => 'https://api.wpmet.com/wp-json/feedback/v1/collect',
 *       'api_key'        => WPMET_FEEDBACK_KEY,
 *       'is_pro'         => false,
 *   ]);
 *
 * Pro plugin (elementskit/elementskit.php):
 *
 *   \Feedback_SDK\Core\SDK::init([
 *       'plugin_name'    => 'ElementsKit Pro',
 *       'plugin_slug'    => 'elementskit',
 *       'plugin_version' => ELEMENTSKIT_PRO_VERSION,
 *       'api_endpoint'   => 'https://api.wpmet.com/wp-json/feedback/v1/collect',
 *       'api_key'        => WPMET_FEEDBACK_KEY,
 *       'is_pro'         => true,
 *   ]);
 *
 * Both will appear separately in the server dashboard under their own slugs,
 * and can be filtered with the is_pro column.
 */


// ─────────────────────────────────────────────────────────────────────────────
// 6. STORING THE API KEY SAFELY
// ─────────────────────────────────────────────────────────────────────────────

/*
 * Never hard-code the API key directly in your plugin if it will be
 * distributed publicly (WordPress.org, GitHub, etc.).
 *
 * Recommended approaches:
 *
 * A) Define in wp-config.php (best for single server):
 *    define( 'WPMET_FEEDBACK_KEY', 'fk_xxxxxxxxxxxxxxxx' );
 *
 * B) Define in your plugin's private config file (not committed to git):
 *    // config.php  (in .gitignore)
 *    define( 'WPMET_FEEDBACK_KEY', 'fk_xxxxxxxxxxxxxxxx' );
 *
 * C) For distributed plugins — it's acceptable to include the key directly
 *    since the key only allows WRITING feedback (not reading data).
 *    The server's rate limiter and HMAC signature provide the protection.
 *
 *    'api_key' => 'fk_xxxxxxxxxxxxxxxx',  // write-only, rate-limited
 */
