<?php
/**
 * Deactivation handler — renders modal overlay, handles AJAX submit/skip.
 *
 * DEACTIVATION URL FIX:
 * The previous implementation tried to rebuild the deactivation URL on the
 * server, which broke when the plugin file basename didn't match the slug
 * (e.g. 'pageflash/pageflash.php') causing "The link you followed has expired".
 *
 * Fix: the JS stores the ORIGINAL href from the deactivate link before
 * intercepting it and sends it as 'deactivate_url' in the AJAX post.
 * The server echoes it back untouched. This way the nonce in the original
 * URL is always valid because it was generated by WordPress for exactly
 * this plugin file path.
 *
 * @package Feedback_SDK\Admin
 */

namespace Feedback_SDK\Admin;

use Feedback_SDK\API\Client;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Class Deactivation
 */
class Deactivation {

	/** @var array<string,mixed> SDK configuration. */
	private array $config;

	/**
	 * @param array<string,mixed> $config SDK configuration.
	 */
	public function __construct( array $config ) {
		$this->config = $config;
	}

	/**
	 * Output the empty overlay <div> into the admin footer.
	 *
	 * The modal HTML is built entirely by modal.js using the localized
	 * config object, so this only needs to exist as a mount point.
	 *
	 * @return void
	 */
	public function render_modal(): void {
		$screen = get_current_screen();
		if ( ! $screen || 'plugins' !== $screen->id ) {
			return;
		}

		echo '<div id="feedback-sdk-modal-' . esc_attr( $this->config['plugin_slug'] ) . '" '
			. 'class="feedback-sdk-overlay" '
			. 'style="display:none;" '
			. 'aria-hidden="true"></div>' . "\n";
	}


	/**
	 * Handle feedback submission.
	 *
	 * 1. Verify nonce + capability.
	 * 2. Sanitize posted fields.
	 * 3. Send payload to the Feedback server (non-blocking).
	 * 4. Return the original deactivation URL back to JS.
	 *
	 * The deactivation URL is sent by JS as `deactivate_url` (the original
	 * href intercepted from the "Deactivate" link). The server echoes it
	 * straight back — it never rebuilds the URL — so the WordPress nonce
	 * embedded in the URL is always valid.
	 *
	 * @return void
	 */
	public function handle_ajax(): void {
		$slug = $this->config['plugin_slug'];
		check_ajax_referer( "feedback_sdk_{$slug}", 'nonce' );

		if ( ! current_user_can( 'activate_plugins' ) ) {
			wp_send_json_error( array( 'message' => __( 'Unauthorized.', 'feedback-sdk' ) ), 403 );
			return;
		}

		$reason         = sanitize_text_field( wp_unslash( $_POST['reason']         ?? '' ) );
		$message        = sanitize_textarea_field( wp_unslash( $_POST['message']    ?? '' ) );
		$competitor     = sanitize_text_field( wp_unslash( $_POST['competitor']     ?? '' ) );
		$gdpr           = ! empty( $_POST['gdpr'] );
		$deactivate_url = esc_url_raw( wp_unslash( $_POST['deactivate_url']         ?? '' ) );

		$payload = array(
			'plugin_name'    => $this->config['plugin_name'],
			'plugin_slug'    => $slug,
			'plugin_version' => $this->config['plugin_version'],
			'reason'         => $reason,
			'message'        => $message,
			'competitor'     => $competitor,
			'site_url'       => get_site_url(),
			'admin_email'    => $gdpr ? get_option( 'admin_email' ) : '',
			'wp_version'     => get_bloginfo( 'version' ),
			'php_version'    => PHP_MAJOR_VERSION . '.' . PHP_MINOR_VERSION,
			'locale'         => get_locale(),
			'is_pro'         => (bool) $this->config['is_pro'],
			'timestamp'      => current_time( 'mysql' ),
		);

		// Allow consumers to modify payload before it is sent.
		$payload = (array) apply_filters( 'feedback_sdk/payload', $payload, $slug );
		$client  = new Client( $this->config['api_endpoint'], $this->config['api_key'] );
		$success = $client->send( $payload );

		do_action( 'feedback_sdk/after_send', $slug, $success, $payload );
		wp_send_json_success( array( 'deactivate_url' => $deactivate_url ) );
	}


	/**
	 * Handle skip (no feedback submitted).
	 *
	 * Returns the original deactivation URL so JS can redirect immediately.
	 *
	 * @return void
	 */
	public function handle_skip(): void {
		$slug = $this->config['plugin_slug'];
		check_ajax_referer( "feedback_sdk_{$slug}", 'nonce' );

		if ( ! current_user_can( 'activate_plugins' ) ) {
			wp_send_json_error( array( 'message' => __( 'Unauthorized.', 'feedback-sdk' ) ), 403 );
			return;
		}

		$deactivate_url = esc_url_raw( wp_unslash( $_POST['deactivate_url'] ?? '' ) );

		wp_send_json_success( array( 'deactivate_url' => $deactivate_url ) );
	}
}
